### ISSUE TITLE
Development brief

### ISSUE THREAD

**Issue by yozness** [TransparenCEE/factchecker-plugin-chrome#10]
Write a clear technical brief of what the plugin is required to do, so the developer knows what to code. Provide a bit of context and outline the goal of the project, then focus on the technical side.

Start from this document > https://docs.google.com/document/d/1C5csr8R7DtYO13UPBcPhOlUO-L0gZUpVuoedUyWwrcs/edit

**Comment by KrzysztofMadejski** [comment]
I'd that has been already distributed among other issues. Shoud we close it?
