### ISSUE TITLE
Chrome extension usage statistics

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#13]
As stated in https://github.com/TransparenCEE/factchecker-plugin-chrome/issues/9#issuecomment-231707499: we need to show how many ppl are using the chrome extension.

**User scenario:** As an administrator I want to know how many people have seen fact-checked statements and how they’ve reached it. 

**API feature:** Querying for any URL should contain a piece of information identifying the way of accessing the Statements (is it being highlighted by plugin? on partner media for user without a plugin? did user navigated from facebook highlight?). How to name it? Origin?

This affects the API spec #1 and extension code #5 (should extension report the usage anonymously, will calls to API be sufficient for monitoring, etc.)

**Comment by KrzysztofMadejski** [comment]
Also on the higlighted statement (#3) the link to the justification should have some `query parameter` informing that this user came to fact-checker website because of the plugin. So we now how much of the fact-checker audience is using the plugin to know more?

**Comment by KrzysztofMadejski** [comment]
Still to implement (I've tested 0.0.4 version)
- [x] the query parameter is not added to the "Read more" link in the popup
- [x] the plugin is not using `client` query param from [API](http://docs.factualkm.apiary.io/#reference/statements/statements-list/statements-in-given-source)
- [x] the plugin is not using `origin` param from [API](http://docs.factualkm.apiary.io/#reference/statements/statements-list/statements-in-given-source)

CC: @voidberg

**Comment by voidberg** [comment]
I've implemented this as follows:
- All API requests send a user token that's generated on the first install of the extension.
- "Read more" has a `client=chrome_extension` param.
- All API requests send `client=chrome_extension` and `origin=site`.

**Comment by KrzysztofMadejski** [comment]
Hi,
Is the url list of articles stored in cache or every visited URL is pinged to the server? 

Concerning API request: the origin param was mainly to track the external referrers.,ie. how many ppl visited this article due to fb highlight. Mainly I'd like to be able to track facebook users. So the use case is: when an user enters the article via facebook timeline highlight the inforamtion is propagated to the API. 

How to do it? I was thinking about injecting the param factcheck-user-origin=facebook to url of the article on facebook. Then on the article itself the extension would check for that param and set origin=facebook in the API call.

Would do you think of this solution?

**Comment by voidberg** [comment]
The cache is not completely implemented right now as the API for `all` became usable yesterday so right now every visit is pinging the server.

Regarding Facebook, I do not think I can do what you want. The issue is that Facebook has javascript on mouseover that performs modifications to the url so, even if I add that parameter, it will be overridden by their js. It also has a weird behaviour that puts a direct link to the article on first share and then, on another page load, transforms it via `l.facebook.com/l.php` or `www.facebook.com/l.php`.

I can give it a shot and see if I can get around the mouseover js but I would keep it as low priority for now.

**Comment by KrzysztofMadejski** [comment]
Ok, let's keep it a low priority. 

Regarding pinging on every url - then having the user token is really invading privacy - all the browsing history is sent to the server. I think this feature should be disabled.

**Comment by voidberg** [comment]
We're not pinging with the actual url but with a md5.

**Comment by KrzysztofMadejski** [comment]
Ok, that's making tracking quite harder. Let's keep this solution.

For future releases: let's change the hash to sha1, md5 is for quite a time known to be reversible.
