### ISSUE TITLE
Common term dictionary

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#14]
I believe that we should create (or better use an existing) common dictionary of terms.  @yozness, could you (and  others of your team) help so make sure we use the language of international fact-checking community?

So should we use the words:
- `statement` or `fact` or `claim`
- `rating` or `truth` or `ruling`
- `justification` or `explanation`
- `website` or `source`

Please add options above by editing my post and provide your comment below.

I'd suggest using the `source` for `any fact-checked online source with an URL: article, video, etc.` because you can fact-check more things than just articles.

Then I'm looking for some word to describe how user get to view highlighted statement (#13): `origin`: `chrome-extension` | `media-partner` ?

**Comment by yozness** [comment]
Hello, I checked with Elena and came back with the following words to be used:
- statement
- rating
- justification / explanation (there is no common word here, so we are free to choose one, I suggest the latter)
- source

Thanks :)

**Comment by KrzysztofMadejski** [comment]
Cool, closing this issue then!
