### ISSUE TITLE
AGPL License

### ISSUE THREAD

**Issue by voidberg** [TransparenCEE/factchecker-plugin-chrome#17]
I don't really have a preference on what we release the code under but I know some people are resistant to GPL licenses so I am wondering if MIT is not a better option?

Was AGPL just an initial pick or are there other reasons for choosing it?

**Comment by KrzysztofMadejski** [comment]
I use aGPL by default to make sure that the code stays open.  It was not discussed though yet.

MIT could be  a sensible option if we would plan to commercialize the code in the future, do you foresee that option?

@yozness what do you think?

**Comment by voidberg** [comment]
I don't foresee that option tbh. As I said, I am fine with AGPL, I brought it up just for curiosity. :)

**Comment by KrzysztofMadejski** [comment]
To be closed when we have published code on Github with LICENSE.md file

**Comment by voidberg** [comment]
Closing this as we have a `LICENSE.md` in the repo now.
