### ISSUE TITLE
TrackJS

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#29]
Hi,

@voidberg I've seen that you are using usage.trackjs.com. Is that necessary? I think that calls to API should be enough for statistics.

**Comment by voidberg** [comment]
I will remove it in the next release. I used it just to track errors when other people were testing it but since nothing came up we can remove it I think.

**Comment by KrzysztofMadejski** [comment]
Or it could be put in the options, if you had the time to develop options page. If not I'm leaving the label to remember about this possibility in the future.

**Comment by KrzysztofMadejski** [comment]
Ping

**Comment by voidberg** [comment]
Will be removed in the next release.

**Comment by voidberg** [comment]
Removed.
