### ISSUE TITLE
Highlighting phrases - design

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#3]
**User scenario:** When I have installed Chrome extension and I view any website with Statements, these Statements should be highlighted, a rating (true, false, etc.) should be provided, together with a link to justification on the fact-checker website.

**API feature:** For any URL the API should provide a list of Statements that appear in this URL.

Design should include (to be discussed):
- highlighting statement
- providing rating in visual form
- linking to factual.ro for full explanation
- information about plugin features (for cases when this will be embedded by partnering media in website html code - #12 )

Acceptance Criteria: Accepted designs for few sources commonly used by factual.ro:
- government website
- parliamentary debate
- official news portal
- some other news portal
- ... ?

**Comment by KrzysztofMadejski** [comment]
Prototype:
![politifact2](https://cloud.githubusercontent.com/assets/849975/16688322/e05545a8-451d-11e6-9d12-f2aa1608ce70.PNG)

**Comment by yozness** [comment]
I think we can do better in terms of design. I will find a web-designer available who can layout something usable and non-intrusive.

Also, potential media partners would be more inclined to partner with us after we have a functional product. It would be easier for me to convince them if I show them a demo.

**Comment by KrzysztofMadejski** [comment]
Design option 1 - https://projects.invisionapp.com/share/HP84X31UK#/screens/178017564
Design option 2 (popup) - https://projects.invisionapp.com/share/8J84WT4AV#/screens/178046025

**Comment by KrzysztofMadejski** [comment]
I'm afraid that Option 2 won't be hovered and seen by everybody.

Anca, how about redesigning option 1 so the highlight comes after the paragraph when it happened, so it doesn't brake the paragraph layout, but still provides information. In Many published materials such technique is used to highlight interesting quotes (the highlight is on the side mostly).

**Comment by voidberg** [comment]
Option 2 is going to be tricky to implement since I have to break the layout of the page and put the quote into it's own box. This can cause havok on pages since each site can have it's own css and odd rules and getting it to work on any random site will be impossible.

**Comment by KrzysztofMadejski** [comment]
Some feedback:

User A: _Option 1 is nicer, but the popup should be wider like in Option 2. The popup should be shown above the statement so one can read further without popup being an obstacle._. User A hasn't seen 'checked by Factual' badge

User B: _Option 2 is preferable, catching an eye. Options should allow to switch to Option 1 if this is too intrusive, but 2 should be the default._ User B has seen the badge 'checked by', but said it's hard to spot it even if you know it's there.

Me: In case of media partner highlights we should go for Option 2, because the users won't know the concept of highlighting. It should be more intrusive, though we should ask mdia partners if they are willing to show it like that. @yozness is it the time to ask them using the layouts?

Me: I though about modyfing Option 2, so the highlight is shown beneath the paragraph where statement is. @voidberg , would this resolve problems in inlining text? Then maybe also the statement could be highlighted.

**Comment by KrzysztofMadejski** [comment]
@voidberg could you comment on my previous post? (about inlining in between paragraphs)

Could both options be implemented and then choosed by user?

**Comment by anca-m** [comment]
Hey, I only now see these comments here.

I think we can go with just one option: option 1( highlight vs) and it should work on mouse over, so even if users are not familiar with the highlight, it is very easy to discover the rating just by scrolling the page. In my opinion Option 2 is a spamy solution in any context especially on news websites that feature tons of advertising. 

I agree with the window to open above the paragraph. And I can make it wider if you think that improves reading.

**Comment by KrzysztofMadejski** [comment]
I'm afraid that in case of highlighting content on media partners website for people that don't have a plugin ( #12) Option 1 won't work. Do an experiment: Please open any article and scroll through it. Do you keep a mouse on the text, or on the side? 

I'm keeping mouse on the side, because otherwise it's an obstacle to reading the text.

Anyways, is it a lot of work to implement option 2 and let the users switch if they want? I don't think so. @voidberg ?

**Comment by voidberg** [comment]
Option 2 will not work for the extension since it should work for all websites and there's a lot of issues with trying to inject a block and modify their layout. E.g.:
- We'd have to split a paragraph, create two, remove the text and insert a div. Other websites might have different markup, multiple child tags or text that crosses elements. Trying to work this out is going to be very error prone and it's enough to break the layout of two websites out of 50 to get the user to uninstall.
- Very wide websites where our box would stretch and look crap.
- A not so wide website where the text is even less wide due to being flushed to the right / left of an image. Our box won't fit.
- Websites with fancy ads that modify the content themselves (like video appears and disappears as you scroll the content).

Putting it at the top, under the title, doesn't work either. How do you figure out which is the content area of a random website? Readability and Apple's version don't get it right in some cases, I doubt that we would.

Option 2 is only usable on a partner website, where we could add some selectors to the config for that website to be able to tell where the title is / content starts and use that to place our box.

**Comment by KrzysztofMadejski** [comment]
Ok, so let's leave it as an option (experimental) to b pursed when media partners agree to join in. Then the feature can also be developed knowing what's their standard layout. 

PS. Now it came to my mind that highlighting content on partners' websites would work also on mobile! Though it's also more work to implement.

I'm closing the issue as we have the designs. Thanks @voidberg for in-depth explanation.

**Comment by KrzysztofMadejski** [comment]
Adding "extension's options" label to remember the possibility to offer different kind of highlighting for users that would like to check it out.
