### ISSUE TITLE
Add CORS Access-Control-Allow-Origin header in API

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#32]
Error received in Firefox (#30): `CORS header ‘Access-Control-Allow-Origin’ missing`

The API should return `Access-Control-Allow-Origin` with specific origin posted in the request or `Access-Control-Allow-Origin: *` if there was not origin provided.

**Comment by voidberg** [comment]
Closed by https://github.com/TransparenCEE/factchecker-wordpress-api/commit/e4b03b15d3ae4cd235354c5d3da9b1f03d2cfb11
