### ISSUE TITLE
Research the browser penetration in country of implementation

### ISSUE THREAD

**Issue by KrzysztofMadejski** [TransparenCEE/factchecker-plugin-chrome#9]
What is the market share of web browsers:
- [ ] in general in Romania
- [ ] among Factual.ro audience 

What percentage of users are on mobile:
- [ ] in general
- [ ] among Factual.ro audience

**Comment by yozness** [comment]
http://gs.statcounter.com/#browser-RO-monthly-201505-201605

For what time span should we look into?

**Comment by KrzysztofMadejski** [comment]
@yozness  I'd say that January - June 2016. Will you share statistics from Factual?

**Comment by yozness** [comment]
The thing is that I have a black hole in statistics because the analytics was not working in the past months :( Let me see what I can gather, maybe I can get some stats from the server.

**Comment by KrzysztofMadejski** [comment]
Ie. http://piwik.org/docs/log-analytics-tool-how-to/

On 11 July 2016 at 12:22, yozness notifications@github.com wrote:

> The thing is that I have a black hole in statistics because the analytics
> was not working in the past months :( Let me see what I can gather, maybe I
> can get some stats from the server.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/TransparenCEE/factchecker-plugin-chrome/issues/9#issuecomment-231697160,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAz4N5F1gjoonTYRN55zGmr2DmCmuPz4ks5qUhl6gaJpZM4I_GyD
> .

## 

_Krzysztof Madejski_
karolina.wysocka@epf.org.plCode for Poland Program Manager /
Koordynator Koduj
Dla Polski http://kodujdlapolski.pl
Product Manager at TransparenCEE.org
krzysztof.madejski@epf.org.pl / +48 664 082 823
- http://epf.org.pl/*

**Comment by yozness** [comment]
![download 20](https://cloud.githubusercontent.com/assets/12371483/16728164/7ab4465c-476d-11e6-8e6b-bd2e99106c66.png)

I have no piwik on the server :( You can see from the graph when the G Analytics was not available. Still, Chrome rulez.

**Comment by KrzysztofMadejski** [comment]
And could you check operating system / screen resolution to check how many
ppl are on mobile?

On 11 July 2016 at 12:44, yozness notifications@github.com wrote:

> [image: download 20]
> https://cloud.githubusercontent.com/assets/12371483/16728164/7ab4465c-476d-11e6-8e6b-bd2e99106c66.png
> 
> I have no piwik on the server :( You can see from the graph when the G
> Analytics was not available. Still, Chrome rulez.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/TransparenCEE/factchecker-plugin-chrome/issues/9#issuecomment-231701269,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAz4NwoSiwKr0zRiTnQ-bB2CIbfIVB8-ks5qUh50gaJpZM4I_GyD
> .

## 

_Krzysztof Madejski_
karolina.wysocka@epf.org.plCode for Poland Program Manager /
Koordynator Koduj
Dla Polski http://kodujdlapolski.pl
Product Manager at TransparenCEE.org
krzysztof.madejski@epf.org.pl / +48 664 082 823
- http://epf.org.pl/*

**Comment by yozness** [comment]
![download 23](https://cloud.githubusercontent.com/assets/12371483/16728754/ef5c39d0-4770-11e6-958c-ae33685d0520.png)

**Comment by KrzysztofMadejski** [comment]
Chrome users make ~63% percent of views. Desktop users ~74% views.  So I'd say that we've justified making desktop-based Chrome extension. :)

Could you get analytics up & running? The end result in metrics of implementing this Chrome extension should be noticeably more views of your webpage. (PS. We need statistics for the Chrome extension as well).

**Comment by yozness** [comment]
Yep, the decision is correct. Yes, I have already asked our sys-admin to install Piwik on the server and have the Google Analytics code in the Factual.ro Wordpress, should work, will check though

**Comment by KrzysztofMadejski** [comment]
Closing as we have researched browser penetration.
